### ISSUE TITLE
upload.php is vulnerable to path traversal attacks

### ISSUE THREAD

**Issue by evilsocket** [alt3kx/wafaray#2]
The `$file_name` variable is [directly taken](https://github.com/alt3kx/wafaray/blob/main/upload.php#L4) from `$_FILES` and not cleaned via `basename` as suggested in the official documentation for [move_uploaded_file](https://www.php.net/manual/en/function.move-uploaded-file.php). This can result in a security vulnerability when an attacker uses  a relative path as file name in order to overwrite other PHP and/or system files (for instance, `$_FILES['image']['name']` might be `../../../../../../var/www/html/index.php`, or `../../../../../../etc/apache2/anything-apache2-has-write-access-to`).

I suggest to use `basename` on the file name and ideally checking the actual mime type of the file via [mime_content_type](https://www.php.net/manual/en/function.mime-content-type.php) since `$_FILES['image']['type']` can be manipulated too.

**Comment by alt3kx** [comment]
Thanks for your comments  , **upload.php** initially was designed for simulate a upload functions (dont forget the "core" engine is the inspection of files) , nevertheless all your suggestions will  take into account for future releases..

**Comment by evilsocket** [comment]
upload.php gets installed along with the other components, the point is not it being the core, but creating a vulnerability in the servers it gets installed to.
