### ISSUE TITLE
Is this tried on production appliances?

### ISSUE THREAD

**Issue by Blason** [alt3kx/wafaray#3]
Hey Folks,

Its a nice project - Is this tried on any production appliances?

**Comment by alt3kx** [comment]
Hello @Blason thanks for your feedback, we received  directly questions and suggestions seems interesting some WAF experts and Architects using it on  k8s ,  docker and AWS small environments (Live)  with big adaptations ,  from our side we are working on upcoming releases  to be  easy and quick deployments e.g  Staging environments or Live environments (micro-services) 

thanks  for your interest. 

Regards
/alt3kx
